---

- name: Include vault variables
  include_vars: inventory/vault.yml

- name: Creating Kubernetes secrets
  kubernetes.core.k8s:
    namespace: "{{ namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: laravelio-secret-data
      type: Opaque
      stringData:
        database_password: "{{ database_password }}"